### ISSUE TITLE
Uncaught ReferenceError: radToDeg is not defined

### ISSUE THREAD

**Issue by timmolendijk** [thomasxiii/photon#1]
When following the simple instructions on http://photon.attasi.com/docs.html I get the following error resulting from invoking `render`.

```
var light = new Photon.Light();
var face = new Photon.Face($('#elementWith3DTransformDefinedOnIt')[0]);
face.render(light, true);
```

This tracks back to the following line: https://github.com/thomasxiii/photon/blob/master/js/photon.js#L131

**Comment by thomasxiii** [comment]
This has been resolved. Thank you for catching it!
